### ISSUE TITLE
Cookies going lost in redirect

### ISSUE THREAD

**Issue by Raffson** [smartninja/wd1-py3-exercises#2]
https://github.com/smartninja/wd1-py3-exercises/blob/dd3c552a25cec2dc7d907c59af7444782d26ecdd/lesson-20/example-github-login/main.py#L39

Removing "samesite='Strict'" fixes the issue on my end, although I'm not sure if this is acceptable in terms of security. I notice that as long as "samesite='Strict'" is present, the redirect doesn't carry along the cookies to the "profile" handler. The weird part is that if I adjust the "profile" handler to the following:
```
@app.route("/profile")
def profile():
    token = request.cookies.get("oauth_token")
    if token:
        github = OAuth2Session(os.environ.get("GITHUB_CLIENT_ID"), token=json.loads(token))
        github_profile_data = github.get('https://api.github.com/user').json()
        return render_template("profile.html", github_profile_data=github_profile_data)
    else:
        response = make_response(redirect(url_for('index')))
        return response
```
I obviously get redirected to "index" first, but if I then try to go to the "profile" page, everything works just fine. It's only during the redirect in the callback that I'm getting an error if I'm using your original code because the cookie dictionary is empty at that point.

Any ideas whether it's safe to leave out "samesite='Strict'"? Or perhaps change the parameter to a different value? Because as long as that parameter's there, I keep getting an exception saying json expects a byte-array since "request.cookies" is empty right after the callback's redirection.

Thanks in advance for your time 😉

**Comment by ramuta** [comment]
@Raffson I think this issue only happens on localhost, right?

If so, create a function that checks whether the environment is localhost or not (or rather if the environment is Heroku, or not - if the production server is on Heroku).

For example, you can check whether the env var "DYNO" exists, this is one of the typical Heroku env vars:

```python
def is_local():
    if "DYNO" in os.environ:
        return False
    return True
```
(p.s.: I haven't tested this function, just wrote it from the top of my head)

Then you can use this function to decide whether to use `samesite='Strict'` or not ;)

**Comment by ramuta** [comment]
P.S.: When you find the solution please make a pull request to this repo :)

**Comment by Raffson** [comment]
@ramuta You're right about the localhost part since I haven't tested this on Heroku yet. I've got a little draft, trying to determine whether the rooturl is equal to "http://localhost/" or "http://127.0.0.1/". It should work properly on the localhost now, but before making the PR I'll try hosting it on Heroku first. Hopefully I can also find a way to actually verify if the code is working as expected.
Meanwhile you can review the changes [here](https://github.com/Raffson/wd1-py3-exercises/commit/02f9304a0ce23bffec292b5cdb9c0db84c8e4e11).

**Comment by Raffson** [comment]
I just tested this on Heroku, turns out it still crashes when "samesite='Strict'" is present. Also my adjustments don't seem to work as I expected in the sense that I'd have to run 'is_local()' every time the callback is triggered instead of running it once and storing the result in a variable. Now I'm wondering whether I'll need them at all since the "samesite" option still causes a crash.

**Comment by ramuta** [comment]
@Raffson Ok, let's get rid of samesite then. Do you want to do a PR or should I remove it?

**Comment by Raffson** [comment]
PR coming up, issue can be closed 👍
