### ISSUE TITLE
wrong template name: should be "all_users.html" not "users.html"

### ISSUE THREAD

**Issue by zrile** [smartninja/wd1-py3-exercises#4]
https://github.com/smartninja/wd1-py3-exercises/blob/5261bf2e04bf04a8b258380dde55bbe79d4b8de3/lesson-21/sql-guess-secret-number/main.py#L159

**Comment by ramuta** [comment]
@zrile Hey Zrinka! 🙂 The template in this example is indeed called `users.html`: https://github.com/smartninja/wd1-py3-exercises/tree/master/lesson-21/sql-guess-secret-number/templates

**Comment by ramuta** [comment]
If you had something else in mind, please let me know, otherwise I'll close this issue 😉

**Comment by zrile** [comment]
Hej Matej, onda u lekciji 21 treba promijeniti upute jer tamo piše da se
template zove all_users 😀

**Comment by zrile** [comment]
Ipak nije, OPROSTI, samo handler se zove all_users.... Zatvori issue, to je
bilo to. Još jednom oprostiii

**Comment by ramuta** [comment]
nema problema 🙂

**Comment by zrile** [comment]
I did the lesson last week and literally copied step by step all the
necessary code, and it always works perfectly but this time the template
names didn't match. Now I can't find the mismatch, have you changed the
code in the lesson am I going crazy? 🤣

pon, 21. pro 2020. 15:41 Zrinka Ratkovic <zrinka.ratkovic@gmail.com> je
napisao:

> Ipak nije, OPROSTI, samo handler se zove all_users.... Zatvori issue, to
> je bilo to. Još jednom oprostiii
>
